In [1]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords 
from sklearn.model_selection import train_test_split
import numpy as np 
from gensim.models import word2vec
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('/Users/camillebustalinio/Desktop/Camille/term 2 project/airbnb data/final_data.csv')

In [3]:
eng_data = data[(data.language=='en')]

In [9]:

# Import the stop word list
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

# Use regular expressions to do a find-and-replace
def preprocessing(x): # x = reviews
    x = str(x)
    #x = x.decode("utf8")
    raw_sentences = tokenizer.tokenize(x.strip())
    raw_sentences_list =  [[item] for item in raw_sentences]
    
    def sentence_to_word(sentence_list):
        try:
            x = re.sub("[^a-zA-Z]", " ", sentence_list)
            x = x.lower().split()
            return x
        except:
            #if x == float:
            return " "
    sentence_list = [sentence_to_word(sentence) for sentence in raw_sentences]
    
    return sentence_list
    


In [4]:
x=eng_data.comments[1]

In [5]:
x

'The place was clean and spacious and the guy there was pretty nice and helpful. Only thing was that the old lady charged me $25 for keeping my luggage for 5 hours.  '

In [63]:
raw_sentences_list =  [[item] for item in raw_sentences]
raw_sentences_list

[['The place was clean and spacious and the guy there was pretty nice and helpful.'],
 ['Only thing was that the old lady charged me $25 for keeping my luggage for 5 hours.']]

In [7]:
def sentence_to_word(sentence_list):
        try:
            x = re.sub("[^a-zA-Z]", " ", sentence_list)
            x = x.lower().split()
            return x
        except:
            #if x == float:
            return " "

In [68]:
[sentence_to_word(sentence) for sentence in raw_sentences]

[['the',
  'place',
  'was',
  'clean',
  'and',
  'spacious',
  'and',
  'the',
  'guy',
  'there',
  'was',
  'pretty',
  'nice',
  'and',
  'helpful'],
 ['only',
  'thing',
  'was',
  'that',
  'the',
  'old',
  'lady',
  'charged',
  'me',
  'for',
  'keeping',
  'my',
  'luggage',
  'for',
  'hours']]

In [10]:
preprocessing(x)

[['the',
  'place',
  'was',
  'clean',
  'and',
  'spacious',
  'and',
  'the',
  'guy',
  'there',
  'was',
  'pretty',
  'nice',
  'and',
  'helpful'],
 ['only',
  'thing',
  'was',
  'that',
  'the',
  'old',
  'lady',
  'charged',
  'me',
  'for',
  'keeping',
  'my',
  'luggage',
  'for',
  'hours']]

In [11]:
word2vec_list = [preprocessing(comment) for comment in eng_data.comments]


In [74]:
word2vec_list[1]

[['the',
  'place',
  'was',
  'clean',
  'and',
  'spacious',
  'and',
  'the',
  'guy',
  'there',
  'was',
  'pretty',
  'nice',
  'and',
  'helpful'],
 ['only',
  'thing',
  'was',
  'that',
  'the',
  'old',
  'lady',
  'charged',
  'me',
  'for',
  'keeping',
  'my',
  'luggage',
  'for',
  'hours']]

In [12]:

eng_data['word2vec'] = word2vec_list
eng_data.head()

/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


Unnamed: 0  listing_id      id_x        date  reviewer_id  \
0           0     8308113  47419975  2015-09-18      6288054   
1           1     3320213  14805088  2014-06-26     17101713   
2           2     3320213  17192435  2014-08-08       182792   
4           4     3320213  18293826  2014-08-24      1104165   
5           5     3320213  18602107  2014-08-28     20421291   

       reviewer_name                                           comments  \
0              Colin  Host was excellent and was contactable / respo...   
1               Faye  The place was clean and spacious and the guy t...   
2  Jocelyne & Pontus  This place wasn't as pleasant as we hoped. Had...   
4             Daniel  Nice room, cool neighbourhood. Note that this ...   
5             Dervla  The listing was accurate and the location was ...   

      id_y                                 name  host_id  \
0  8308113  Luxury Elegant Lrg Studio PacHeight  8739745   
1  3320213   Private Room with TWO Double Beds.  3553372   
2  3320213   Private Room with TWO Double Beds.  3553372   
4  3320213   Private Room with TWO Double Beds.  3553372   
5  3320213   Private Room with TWO Double Beds.  3553372   

                         ...                         price  minimum_nights  \
0                        ...                           350               1   
1                        ...                           199               1   
2                        ...                           199               1   
4                        ...                           199               1   
5                        ...                           199               1   

  number_of_reviews  last_review  reviews_per_month  \
0                 1   2015-09-18               0.10   
1                29   2015-10-11               1.18   
2                29   2015-10-11               1.18   
4                29   2015-10-11               1.18   
5                29   2015-10-11               1.18   

  calculated_host_listings_count  availability_365  language  price_tag  \
0                              1                 0        en    neutral   
1                             11               365        en        exp   
2                             11               365        en        exp   
4                             11               365        en        exp   
5                             11               365        en        exp   

                                            word2vec  
0  [[host, was, excellent, and, was, contactable,...  
1  [[the, place, was, clean, and, spacious, and, ...  
2  [[this, place, wasn, t, as, pleasant, as, we, ...  
4  [[nice, room, cool, neighbourhood], [note, tha...  
5  [[the, listing, was, accurate, and, the, locat...  

[5 rows x 26 columns]

In [14]:
exp_eng_data = eng_data[(eng_data.price_tag=='exp')]
cheap_eng_data = eng_data[(eng_data.price_tag=='cheap')]
len(exp_eng_data), len(cheap_eng_data),len(exp_eng_data)+len(cheap_eng_data) 

(9240, 42928, 52168)

In [111]:
X=eng_data.word2vec
y=eng_data.price_tag


In [17]:
sentences_list = []
for sentences in X:
    sentences_list += [sentence for sentence in sentences]

In [18]:
sentences_list[1]

['would', 'definitely', 'recommend', 'this', 'location']

/Applications/anaconda/lib/python3.5/site-packages/gensim/utils.py:1015: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")


In [126]:
num_features = 50
min_word_count = 40 
num_workers = 4       
context = 5          
downsampling = 1e-3 

print('begin w2v')
# Initialize and train the model (this will take some time)


model = word2vec.Word2Vec(sentences_list, workers=num_workers, \
            size=num_features, min_count = min_word_count, \
            window = context, sample = downsampling)

model.init_sims(replace=True)

print('w2v model :)')

# save the model for later use
model_name = "airbnb_word2vec"
model.save(model_name)


begin w2v
w2v model :)


In [127]:

model.doesnt_match("king queen girl crown".split())


'girl'

In [128]:
model.most_similar("expensive")

[('pricey', 0.7832764983177185),
 ('overpriced', 0.7489678859710693),
 ('prices', 0.7069512605667114),
 ('unusual', 0.6785041689872742),
 ('crowded', 0.6601059436798096),
 ('reasonable', 0.6468909978866577),
 ('challenging', 0.6389502882957458),
 ('alternative', 0.6361240744590759),
 ('paying', 0.6230862736701965),
 ('rare', 0.6160271167755127)]

In [129]:
model.most_similar("cheap")

[('inexpensive', 0.7085990905761719),
 ('cabs', 0.6705433130264282),
 ('reasonable', 0.660757303237915),
 ('lyft', 0.6361374258995056),
 ('central', 0.6324213147163391),
 ('uberpool', 0.6147738695144653),
 ('taxis', 0.6041051745414734),
 ('convenient', 0.5901927351951599),
 ('affordable', 0.5866581201553345),
 ('downtown', 0.5842646956443787)]

In [130]:
model['awesome']

array([ 0.12127654,  0.08784179,  0.18817513,  0.17766376,  0.18350889,
       -0.06299261, -0.04999506,  0.11631627,  0.16725485, -0.04495953,
       -0.16157889, -0.03212997, -0.04244867, -0.08226436,  0.10065619,
        0.11771405, -0.06446877,  0.15136918,  0.01015914, -0.007449  ,
        0.29764175,  0.04519204,  0.13532314,  0.04683873, -0.17327774,
        0.05752533,  0.00405649,  0.08557403,  0.10775098, -0.27687329,
       -0.01155883, -0.13926803,  0.07233366, -0.25653321, -0.10377131,
        0.1493576 , -0.25137556,  0.2694765 , -0.21393067,  0.06235608,
        0.0869219 , -0.00464305, -0.03658104, -0.2792488 , -0.13039424,
        0.03638535, -0.19918096,  0.09410358,  0.17771636, -0.07405628], dtype=float32)

In [27]:


def makeFeatureVec(words, model, num_features):
    # Pre-initialize an empty numpy array (for speed)
    featureVec = np.zeros((num_features,),dtype="float32")
    nwords = 0.

    # Convert it to a set, for speed 
    index2word_set = set(model.index2word)

    # Loop over each word in the review and, if it is in the model's vocaublary, add its feature vector to the total
    for word in words:
        if word in index2word_set: 
            nwords = nwords + 1.
            featureVec = np.add(featureVec,model[word])

    # Divide the result by the number of words to get the average
    featureVec = np.divide(featureVec,nwords)
    return featureVec


def getAvgFeatureVecs(reviews, model, num_features):
    # Given a set of reviews (each one a list of words), calculate the average feature vector for each one and return a 2D numpy array 

    # Initialize a counter
    counter = 0.

    # Preallocate a 2D numpy array, for speed
    reviewFeatureVecs = np.zeros((len(reviews),num_features),dtype="float32")

    # Loop through the reviews
    for review in reviews:
        # Print a status message every 1000th review
        if counter%1000. == 0.:
            print("Review %d of %d" % (counter, len(reviews)))

        # Call the function (defined above) that makes average feature vectors
        reviewFeatureVecs[counter] = makeFeatureVec(review, model, \
           num_features)

        # Increment the counter
        counter = counter + 1.
    return reviewFeatureVecs

In [28]:
import re
import nltk
from nltk.corpus import stopwords # Import the stop word list
from nltk.stem import WordNetLemmatizer


In [29]:


def review_to_wordlist(x, remove_stopwords=True):
    word_list = []
    for sentence in x:
        for word in sentence:
            word_list.append(word)
    
    wordnet_lemmatizer = WordNetLemmatizer()

    if remove_stopwords:
        stops = set(stopwords.words("english"))
        word_list = [wordnet_lemmatizer.lemmatize(word) for word in word_list if word not in stops]
    return word_list



In [131]:
review_to_wordlist(X[0])
#print(X_train[1])

['host',
 'excellent',
 'contactable',
 'responsive',
 'time',
 'would',
 'definitely',
 'recommend',
 'location']

In [132]:
#X_train_wl = [map(review_to_wordlist, X_train)]
#X_test_wl = [map(review_to_wordlist, X_test)]

exp_wl = [review_to_wordlist(comment) for comment in exp_eng_data.word2vec]
cheap_wl = [review_to_wordlist(comment) for comment in cheap_eng_data.word2vec]
exp_wl[3],cheap_wl[4]

(['listing',
  'accurate',
  'location',
  'good',
  'slight',
  'smell',
  'curry',
  'hallway',
  'never',
  'room',
  'never',
  'bothered',
  'u',
  'much',
  'also',
  'hot',
  'night',
  'left',
  'window',
  'open',
  'heard',
  'lot',
  'noise',
  'manageable',
  'check',
  'quick',
  'easy',
  'maybe',
  'little',
  'abrupt',
  'everything',
  'needed',
  'achieved',
  'wifi',
  'password',
  'readily',
  'available',
  'signal',
  'strong',
  'thought',
  'pricing',
  'maybe',
  'little',
  'pricy',
  'area',
  'good',
  'lot',
  'good',
  'place',
  'eat',
  'nearby',
  'transport',
  'link',
  'great',
  'muni',
  'two',
  'black',
  'away',
  'mission',
  'street',
  'take',
  'straight',
  'downtown',
  'would',
  'definitely',
  'recommend',
  'place',
  'someone',
  'looking',
  'basic',
  'last',
  'minute',
  'accommodation',
  'good',
  'location'],
 ['stayed',
  'laykoons',
  'apartment',
  'week',
  'really',
  'enjoyed',
  'time',
  'apartment',
  'much',
  'large

In [104]:
X_train,X_test, y_train, y_test = train_test_split(X_wl,y)
len(X_train),len(X_test), len(y_train), len(y_test)

(121485, 40496, 121485, 40496)

In [133]:
exp_DataVecs = getAvgFeatureVecs(exp_wl, model, num_features )
exp_DataVecs[7]

Review 0 of 9240
Review 1000 of 9240
Review 2000 of 9240
Review 3000 of 9240
Review 4000 of 9240
Review 5000 of 9240
Review 6000 of 9240
Review 7000 of 9240
Review 8000 of 9240
Review 9000 of 9240


array([ 0.02678226,  0.03893098,  0.00807955, -0.03790541,  0.04673043,
        0.00959679,  0.16254832,  0.04318785,  0.02441642,  0.01412766,
       -0.0049756 , -0.04537656,  0.03605764, -0.11092427, -0.05177397,
        0.08739338,  0.00954814, -0.10272437, -0.01943629, -0.03009699,
       -0.02316828, -0.01461026, -0.01517702,  0.01000217, -0.01122252,
       -0.07412529, -0.05463564, -0.06995891,  0.03898394, -0.09025746,
        0.02778273, -0.05908651,  0.0217025 ,  0.04917948, -0.18023346,
       -0.00972061, -0.08939122,  0.06911238,  0.01645757,  0.05939141,
       -0.04112816, -0.07851529, -0.09523399,  0.06264875,  0.04230859,
       -0.00774647,  0.01478744, -0.06059278,  0.07004013,  0.02467293], dtype=float32)

In [134]:
cheap_DataVecs = getAvgFeatureVecs(cheap_wl, model, num_features )
len(cheap_DataVecs[13])

Review 0 of 42928
Review 1000 of 42928
Review 2000 of 42928
Review 3000 of 42928
Review 4000 of 42928
Review 5000 of 42928
Review 6000 of 42928
Review 7000 of 42928
Review 8000 of 42928
Review 9000 of 42928
Review 10000 of 42928
Review 11000 of 42928
Review 12000 of 42928
Review 13000 of 42928
Review 14000 of 42928
Review 15000 of 42928
Review 16000 of 42928
Review 17000 of 42928
Review 18000 of 42928
Review 19000 of 42928
Review 20000 of 42928
Review 21000 of 42928
Review 22000 of 42928
Review 23000 of 42928
Review 24000 of 42928
Review 25000 of 42928
Review 26000 of 42928
Review 27000 of 42928
Review 28000 of 42928
Review 29000 of 42928
Review 30000 of 42928
Review 31000 of 42928
Review 32000 of 42928
Review 33000 of 42928
Review 34000 of 42928
Review 35000 of 42928
Review 36000 of 42928
Review 37000 of 42928
Review 38000 of 42928
Review 39000 of 42928
Review 40000 of 42928
Review 41000 of 42928
Review 42000 of 42928


50

In [135]:
exp_DataVecs[[12,13]]

array([[ 0.04755645, -0.00167838, -0.01962808, -0.06741405,  0.01089127,
         0.06410567,  0.12480619,  0.09225535, -0.07114873,  0.01717472,
        -0.0168408 , -0.04294909,  0.04872614, -0.04396426, -0.06518949,
         0.02215939, -0.04208612, -0.11247621,  0.02784273,  0.02358133,
        -0.02207324, -0.06871423, -0.04975123, -0.0015294 , -0.01553071,
         0.02248274, -0.05397125, -0.03242316, -0.00498694, -0.06667902,
         0.02439507, -0.00981731,  0.00234602,  0.01202132, -0.09368477,
        -0.0121548 , -0.06120722,  0.01175749,  0.05998155,  0.0380748 ,
        -0.05416548,  0.0123213 , -0.04799069,  0.08419929, -0.00048272,
         0.0489191 ,  0.02218951, -0.04107046,  0.04497211,  0.0017595 ],
       [ 0.0037099 ,  0.04275937, -0.01245425, -0.00937239,  0.02915253,
         0.00746397,  0.06555413,  0.02137936,  0.05343761,  0.07152858,
         0.03710501, -0.01553633,  0.04652159, -0.02799917,  0.05030333,
         0.10235712, -0.01793932, -0.00562976, -0.

In [117]:
exp_n = len(exp_eng_data)
cheap_n=len(cheap_eng_data)
exp_n_samples = int(1300*exp_n/(exp_n+cheap_n))
cheap_n_samples = int(1300*cheap_n/(exp_n+cheap_n))+1
exp_n, cheap_n,exp_n_samples, cheap_n_samples, exp_n_samples+cheap_n_samples

(9240, 42928, 230, 1070, 1300)

In [98]:
def sample_1300():
    random_exp = np.random.randint(0,exp_n,exp_n_samples)
    random_cheap=np.random.randint(0,cheap_n,cheap_n_samples)
    X=np.concatenate((exp_DataVecs[random_exp],cheap_DataVecs[random_cheap]),axis=0)
    #y=np.concatenate((exp_eng_data.price_tag[random_exp],cheap_eng_data.price_tag[random_cheap]),axis=0)
    return X

In [102]:

random_exp = np.random.randint(0,exp_n,3)
random_cheap=np.random.randint(0,cheap_n,3)
#X=np.concatenate(exp_DataVecs[random_exp],cheap_DataVecs[random_cheap])
#y=np.concatenate((exp_eng_data.price_tag[random_exp],cheap_eng_data.price_tag[random_cheap]),axis=0)
#y=np.array(np.concatenate(([['exp']*exp_n_samples],[['cheap']*cheap_n_samples]),axis=0))
y=np.array(['exp']*exp_n_samples,['cheap']*cheap_n_samples)
y

TypeError: data type not understood

In [104]:
np.unique(exp_eng_data.price_tag), len(exp_eng_data.price_tag)

(array(['exp'], dtype=object), 9240)

In [105]:
exp_eng_data.price_tag

1         exp
2         exp
4         exp
5         exp
6         exp
7         exp
8         exp
9         exp
10        exp
11        exp
12        exp
13        exp
14        exp
15        exp
16        exp
17        exp
18        exp
19        exp
20        exp
21        exp
22        exp
23        exp
24        exp
25        exp
26        exp
28        exp
29        exp
679       exp
680       exp
1019      exp
         ... 
169607    exp
169608    exp
169609    exp
169610    exp
169611    exp
169612    exp
169613    exp
169614    exp
169615    exp
169616    exp
169617    exp
169618    exp
169619    exp
169620    exp
169621    exp
169622    exp
169623    exp
169624    exp
169625    exp
169626    exp
169627    exp
169628    exp
169629    exp
169707    exp
169708    exp
169709    exp
169710    exp
169711    exp
169712    exp
169713    exp
Name: price_tag, dtype: object

In [92]:
random_exp, random_cheap

(array([9166, 2360, 8793]), array([39401, 11611,  2376]))

In [95]:
y

array([['exp', 'exp', 'exp'],
       ['cheap', 'cheap', 'cheap']], 
      dtype='<U5')

In [88]:
len(exp_eng_data.price_tag)

9240

In [63]:
random_exp, random_cheap

(array([2682, 4682, 8383]), array([22221,   181,   356]))

In [67]:
np.concatenate((exp_DataVecs[random_exp],cheap_DataVecs[random_cheap]),axis=0)

array([[ 0.00267449,  0.0134945 ,  0.01952867, ..., -0.02968097,
        -0.05948286, -0.04449563],
       [-0.02713343,  0.02143814, -0.0038173 , ..., -0.00012941,
         0.00395378, -0.01223448],
       [ 0.00132237,  0.00630784, -0.0009618 , ...,  0.02306151,
         0.05571912,  0.04475218],
       [-0.01960815,  0.01942927, -0.00918256, ...,  0.02507635,
        -0.0099659 ,  0.03595438],
       [-0.00647312,  0.02243038, -0.00465661, ..., -0.0031122 ,
        -0.01165516,  0.0241308 ],
       [-0.00434918,  0.02403334, -0.01766017, ...,  0.00776346,
         0.00466764,  0.00039289]], dtype=float32)

In [73]:
X_train, y_train=sample_1300()
X_test, y_test = sample_1300()

In [78]:
y_train

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [136]:
X_Datavecs=np.concatenate((exp_DataVecs,cheap_DataVecs),axis=0)
X_Datavecs

array([[ 0.03252693,  0.01478382,  0.00282546, ..., -0.10158304,
         0.09401321,  0.01120427],
       [ 0.05036823,  0.03773965,  0.02604673, ..., -0.001945  ,
         0.06997605,  0.0066389 ],
       [ 0.04656626, -0.02710426,  0.0234201 , ...,  0.03605892,
         0.15647212, -0.00844479],
       ..., 
       [ 0.01199672, -0.02221547, -0.00865069, ...,  0.00790429,
         0.05476882,  0.00096489],
       [ 0.00805571,  0.00509227, -0.0515242 , ..., -0.06410341,
         0.07748736,  0.01586029],
       [-0.00146464, -0.01314441, -0.01517062, ..., -0.01791876,
         0.01314195,  0.02509518]], dtype=float32)

In [137]:
y=eng_data[(eng_data.price_tag!='neutral')].price_tag
y

1           exp
2           exp
4           exp
5           exp
6           exp
7           exp
8           exp
9           exp
10          exp
11          exp
12          exp
13          exp
14          exp
15          exp
16          exp
17          exp
18          exp
19          exp
20          exp
21          exp
22          exp
23          exp
24          exp
25          exp
26          exp
28          exp
29          exp
30        cheap
31        cheap
32        cheap
          ...  
169611      exp
169612      exp
169613      exp
169614      exp
169615      exp
169616      exp
169617      exp
169618      exp
169619      exp
169620      exp
169621      exp
169622      exp
169623      exp
169624      exp
169625      exp
169626      exp
169627      exp
169628      exp
169629      exp
169707      exp
169708      exp
169709      exp
169710      exp
169711      exp
169712      exp
169713      exp
169726    cheap
169727    cheap
169729    cheap
169730    cheap
Name: price_tag, dtype: 

In [138]:
X_train,X_test, y_train, y_test = train_test_split(X_Datavecs,y)
len(X_train),len(X_test), len(y_train), len(y_test)

(39126, 13042, 39126, 13042)

In [110]:
print('READY TO ML!!!')

READY TO ML!!!


In [76]:
from sklearn.ensemble import RandomForestClassifier



In [141]:
randomforest = RandomForestClassifier( n_estimators = 10)
randomforest.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [190]:
y_predict = randomforest.predict(testDataVecs[:1300])
y_test_sample = y_test[:1300]

In [148]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [192]:
print("Accuracy:", sum(y_predict==y_test_sample)/len(y_test_sample))
print("Precision:", precision_score(y_predict,y_test_sample, average="macro") )
print("Recall:", recall_score(y_predict,y_test_sample, average="macro") ) 
print("F1:", f1_score(y_predict,y_test_sample, average="macro") ) 


Accuracy: 0.684615384615
Precision: 0.332056002788
Recall: 0.295656724228
F1: 0.28042475695


/Applications/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1115: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/Applications/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [151]:
#weighted metrics, since groups are not balanced

print("Precision:", precision_score(y_predict,y_test_sample, average="weighted") )
print("Recall:", recall_score(y_predict,y_test_sample, average="weighted") )
print("F1:", f1_score(y_predict,y_test_sample, average="weighted") )


Precision: 0.931562857417
Recall: 0.677692307692
F1: 0.780546923864


/Applications/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1115: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/Applications/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [193]:
print("Rows: Actual, Columns: Predicted")
print('cheap', 'neutral', 'exp')
confusion_matrix(y_predict,y_test_sample, labels = ['cheap', 'neutral', 'exp'])

Rows: Actual, Columns: Predicted
cheap neutral exp


array([[  5,  17,   4],
       [328, 885,  61],
       [  0,   0,   0]])

In [155]:
from sklearn.naive_bayes import MultinomialNB

In [194]:
#multinomial NaiveBayes

clf = MultinomialNB()
# Call fit method
clf.fit(trainDataVecs[:100],y_train[:100])

ValueError: Input X must be non-negative

In [157]:
from sklearn.svm import SVC

In [204]:
svm_clf=SVC(C=1, gamma=0.1)
svm_clf.fit(trainDataVecs[:1300],y_train[:1300])
svm_clf.score(testDataVecs[:10000], y_test[:10000])

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [202]:
y_train[[56,90,889,75]]


56       cheap
90       cheap
889    neutral
75       cheap
Name: price_tag, dtype: object